name: calculator
description: "A new Flutter project."

publish_to: 'none'  
  
version: 1.0.0+1

environment:
  sdk: ^3.7.2
 
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dropdown_button2: ^2.3.9
  awesome_dialog: ^3.2.1
  salomon_bottom_bar: ^3.3.2
  awesome_bottom_bar: ^1.2.1
  google_fonts: ^6.2.1
  animations: ^2.0.11
  google_nav_bar: ^5.0.7
  form_builder_validators: ^11.1.2
  flutter_form_builder: ^9.7.0
  awesome_snackbar_content: ^0.1.2
  shared_preferences: ^2.2.2
  flutter_otp_text_field: ^1.1.1
  http: ^1.0.0
  modal_bottom_sheet: ^3.0.0
  carousel_slider: ^5.1.1
  flutter_rating_bar: ^4.0.1
  expandable_text: ^2.3.0
  visibility_detector: ^0.4.0+2
  loading_animation_widget: ^1.2.0
  file_picker: ^10.2.0
  video_player: ^2.10.0
  google_maps_flutter: ^2.12.3
  geolocator: ^14.0.2
  fl_chart: ^0.66.0
  image_picker: ^1.1.1
  intl: ^0.19.0
  add_to_cart_animation: ^2.0.4
  permission_handler: ^11.4.0
  flutter_image_compress: ^2.4.0
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  smooth_page_indicator:
  easy_stepper: ^0.8.5+1
  collection: ^1.19.1
  flutter_riverpod: ^2.6.1
  math_expressions: ^3.0.0
  decimal: ^3.2.4
  provider: ^6.1.5+1
  speech_to_text: ^7.3.0
  share_plus: ^11.1.0
  function_tree: ^0.9.1
  pdf: ^3.11.3
  printing: ^5.14.2
  



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
